local panels = {
  sys = {
    title = "SYS",
    column = "left",
    x = 28,
    y = 40,
    width = 520,
    height = 792,
    boxes = {
      cpu = {
        x = 16,
        y = 104,
        width = 488,
        height = 184,
        title_source = "cpu_box_title",
      },
      gpu = {
        x = 16,
        y = 320,
        width = 488,
        height = 184,
        title_source = "gpu_box_title",
      },
      storage = {
        x = 16,
        y = 536,
        width = 488,
        height = 184,
        title_source = "storage_box_title",
      },
    },
  },
  tme = {
    title = "TME",
    column = "mid",
    x = 604,
    y = 40,
    width = 520,
    height = 584,
    boxes = {
      clock = {
        x = 16,
        y = 104,
        width = 488,
        height = 184,
        title_source = "clock_box_title",
      },
      calendar = {
        x = 16,
        y = 320,
        width = 488,
        height = 248,
        title_source = "calendar_box_title",
      },
    },
  },
  wxr = {
    title = "WXR",
    column = "right",
    x = 1188,
    y = 40,
    width = 520,
    height = 888,
    boxes = {
      current = {
        x = 16,
        y = 104,
        width = 488,
        height = 184,
        title_source = "current_box_title",
      },
      forecast = {
        x = 16,
        y = 320,
        width = 488,
        height = 296,
        title_source = "forecast_box_title",
      },
      station_model = {
        x = 16,
        y = 648,
        width = 488,
        height = 224,
        title_source = "station_model_box_title",
      },
    },
  },
  net = {
    title = "NET",
    column = "left",
    x = 28,
    y = 880,
    width = 520,
    height = 456,
    boxes = {
      primary = {
        x = 16,
        y = 88,
        width = 488,
        height = 184,
        title_source = "net_box_title",
      },
      vlan = {
        x = 16,
        y = 304,
        width = 488,
        height = 136,
        title_source = "vlan_box_title",
      },
    },
  },
  orb = {
    title = "ORB",
    column = "mid",
    footer_label = "OPERATIONAL SYSTEM ARCHITECTURE",
    footer_label_font_pt = 14,
    footer_machine_label_font_pt = 12,
    footer_version_label_font_pt = 10,
    footer_machine_label_gap = 22,
    footer_version_label_gap = 64,
    footer_label_y = 36,
    x = 604,
    y = 672,
    width = 520,
    height = 560,
    boxes = {
      celestial = {
        x = 16,
        y = 88,
        width = 488,
        height = 200,
        title_source = "celestial_box_title",
      },
      terminator = {
        x = 16,
        y = 360,
        width = 488,
        height = 184,
        title_source = "terminator_box_title",
      },
    },
  },
  env = {
    title = "ENV",
    column = "right",
    x = 1188,
    y = 978,
    width = 520,
    height = 360,
    boxes = {
      atmos = {
        x = 16,
        y = 88,
        width = 488,
        height = 256,
        title_source = "atmos_box_title",
      },
    },
  },
}

return panels
